### ISSUE TITLE
Add `INSERT` and `UPDATE` keywords

### ISSUE THREAD

**Issue by piranna** [avz/node-jl-sql-api#2]
Add `INSERT` and `UPDATE` keywords to allow to add and modify data on the json-lf datastore, just by adding new lines to the end of the file and in the case of the `UPDATE` keyword removing the old one first (so it would make sense to also implement a `DELETE` keyword and maybe some kind of transaction mechanism, so the `UPDATE` would be implemented as a `DELETE` + `INSERT`).

I would also add an option to set a limit in the file size, so if the about-to-write line makes the file to be bigger than this value (easy to implement by just having the current size of the file and the length of the line) just write it in a new file, maybe with an identifier at the end of its filename so later the two (or more) files could be loaded at the same time. The store of the register would check what file has enough space and select it, but maybe this would make it enough complex to make it its own module, isn't it?

**Comment by avz** [comment]
This library manipulates the streams but not files. So if you want to change the contents of the file, it is enough to write it to the query input, save output to a temporary file and, when it finishes successfully, replace the old file with the new one.

Similarly, to perform the `INSERT` simply add additional objects to the stream, and this can be done by conventional methods NodeJS. There is another problem - the inability to conveniently define complex objects directly in SQL.

But `UPDATE` and `DELETE` I'll add. I myself don't need them, but if they need someone else, why not to implement :) Wait for the new version this week.

**Comment by piranna** [comment]
> This library manipulates the streams but not files. So if you want to change the contents of the file, it is enough to write it to the query input, save output to a temporary file and, when it finishes successfully, replace the old file with the new one.

Good point, I was not fully conscious about this library being only streams based, makes sense :-) Maybe the multi-file backend would be implemented in another module that manages them transparently in a line-feed basis...


> There is another problem - the inability to conveniently define complex objects directly in SQL.

We could raise an error here, or just store them but access only to the first level being its internal structure like an opaque blob from the SQL perspective, or maybe expand the SQL syntax to allow a dot-based syntax to access to the internal elements... The only complexity I see here is about the internal references, but if we don't allow them and consider each register as an atomic and isolated element, we should not have problems here.


> But UPDATE and DELETE I'll add. I myself don't need them, but if they need someone else, why not to implement :) Wait for the new version this week.

Cool! :-) Take a look to `INSERT` too, since it would just be a matter of adding a new entry at the end of the stream :-)

**Comment by avz** [comment]
> or maybe expand the SQL syntax to allow a dot-based syntax to access to the internal elements...

this is already implemented: `SELECT * WHERE first.second.third = 3`

Today I added a few new features that will be in version 1.4.0 that will be released after adding `UPDATE`:

#### JSON-compatible constant values

```
SELECT {"some": {"complex": "object"}} AS field
```

 #### `DELETE`

```
DELETE WHERE some.key.in.row = 'value'
```

 #### `INSERT`

```
INSERT {"row": 1}, {"row": 2}, {"row": 3}
```

**Comment by piranna** [comment]
>> or maybe expand the SQL syntax to allow a dot-based syntax to access to the internal elements...
> this is already implemented: SELECT * WHERE first.second.third = 3

Yes, that's exactly what I was talking about :-)


> Today I added a few new features that will be in version 1.4.0 that will be released after adding UPDATE:

Wooho!!! :-D

**Comment by avz** [comment]
New version was released

## `v1.4.0` (2016-12-14)

* Added support for constant JSON-values
* Support for `DELETE WHERE` queries
* Support for `INSERT {object}[,{object}]` queries. Rows just was aded to end of the input stream
* Support for `UPDATE` queries
* Added support for E-notation for floating numbers
* Support for `SELECT *, [fields...]`
